### ISSUE TITLE
TIS平台自身的MySQL连接URL要加 useSSL=false 参数

### ISSUE THREAD

**Issue by ChenShuai1981** [qlangtech/tis#130]
在tis-web-config/config.properties文件中改用mysql数据库，如下
```
project.name=TIS
runtime=daily

tis.datasource.type=mysql
tis.datasource.url=127.0.0.1
tis.datasource.port=3306
tis.datasource.username=root
tis.datasource.password=root
tis.datasource.dbname=tis_console
zk.host=127.0.0.1:2181/tis/cloud

assemble.host=127.0.0.1
tis.host=127.0.0.1
```

启动前后端服务，访问http://localhost:4200时后端服务会抛错，如下：
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
 at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171)
 at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
 at sun.security.ssl.TransportContext.kickstart(TransportContext.java:220)
 at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:437)
 at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:415)
 at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:186)
 ... 69 more

修复方法是在 tis-common-dao/src/main/java/com/qlangtech/tis/manage/spring/TISDataSourceFactory.java 
```
"?useUnicode=yes&amp;characterEncoding=utf8");
```
改为
```
"?useSSL=false&useUnicode=yes&amp;characterEncoding=utf8");
```
重新编译运行再访问就不会抛错了。

**Comment by baisui1981** [comment]
收到

**Comment by baisui1981** [comment]
complete
