### ISSUE TITLE
[hudi]hudi DeltaStreamer 执行过程中tpi包并发修改出错

### ISSUE THREAD

**Issue by baisui1981** [qlangtech/tis#133]
hudi DeltaStreamer 执行过程中tpi包并发修改出错
``` shell
Caused by: java.lang.RuntimeException: org.apache.hudi.exception.HoodieException: org.apache.hudi.exception.HoodieException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.hudi.client.utils.LazyIterableIterator.next(LazyIterableIterator.java:121)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsBytes(MemoryStore.scala:349)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1182)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hudi.exception.HoodieException: org.apache.hudi.exception.HoodieException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.hudi.execution.SparkLazyInsertIterable.computeNext(SparkLazyInsertIterable.java:93)
	at org.apache.hudi.execution.SparkLazyInsertIterable.computeNext(SparkLazyInsertIterable.java:36)
	at org.apache.hudi.client.utils.LazyIterableIterator.next(LazyIterableIterator.java:119)
	... 23 common frames omitted
Caused by: org.apache.hudi.exception.HoodieException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.hudi.common.util.queue.BoundedInMemoryExecutor.execute(BoundedInMemoryExecutor.java:147)
	at org.apache.hudi.execution.SparkLazyInsertIterable.computeNext(SparkLazyInsertIterable.java:89)
	... 25 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.hudi.common.util.queue.BoundedInMemoryExecutor.execute(BoundedInMemoryExecutor.java:141)
	... 26 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at com.alibaba.datax.plugin.writer.hudi.TISHadoopFileSystemGetter.getHadoopFileSystem(TISHadoopFileSystemGetter.java:95)
	at org.apache.hudi.common.fs.FSUtils.getFs(FSUtils.java:112)
	at org.apache.hudi.common.table.HoodieTableMetaClient.getFs(HoodieTableMetaClient.java:256)
	at org.apache.hudi.io.HoodieWriteHandle.getFileSystem(HoodieWriteHandle.java:240)
	at org.apache.hudi.io.HoodieIOHandle.<init>(HoodieIOHandle.java:38)
	at org.apache.hudi.io.HoodieWriteHandle.<init>(HoodieWriteHandle.java:111)
	at org.apache.hudi.io.HoodieCreateHandle.<init>(HoodieCreateHandle.java:87)
	at org.apache.hudi.io.HoodieCreateHandle.<init>(HoodieCreateHandle.java:74)
	at org.apache.hudi.io.CreateHandleFactory.create(CreateHandleFactory.java:46)
	at org.apache.hudi.execution.CopyOnWriteInsertHandler.consumeOneRecord(CopyOnWriteInsertHandler.java:83)
	at org.apache.hudi.execution.CopyOnWriteInsertHandler.consumeOneRecord(CopyOnWriteInsertHandler.java:40)
	at org.apache.hudi.common.util.queue.BoundedInMemoryQueueConsumer.consume(BoundedInMemoryQueueConsumer.java:37)
	at org.apache.hudi.common.util.queue.BoundedInMemoryExecutor.lambda$null$2(BoundedInMemoryExecutor.java:121)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.qlangtech.tis.plugin.PluginAndCfgsSnapshot.dynamicLoad(PluginAndCfgsSnapshot.java:428)
	at com.qlangtech.tis.plugin.PluginAndCfgsSnapshot.synchronizTpisAndConfs(PluginAndCfgsSnapshot.java:344)
	at com.alibaba.datax.plugin.writer.hudi.TISHadoopFileSystemGetter.getHadoopFileSystem(TISHadoopFileSystemGetter.java:81)
	... 16 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.qlangtech.tis.extension.PluginWrapper.computeShortName(PluginWrapper.java:318)
	at com.qlangtech.tis.extension.impl.ClassicPluginStrategy.getShortName(ClassicPluginStrategy.java:105)
	at com.qlangtech.tis.extension.PluginManager.dynamicLoad(PluginManager.java:142)
	at com.qlangtech.tis.plugin.PluginAndCfgsSnapshot.dynamicLoad(PluginAndCfgsSnapshot.java:425)
	... 18 common frames omitted
```

**Comment by baisui1981** [comment]
complete
