### ISSUE TITLE
安装TIS后，我运行FlinkSql时总是提示java.lang.IllegalStateException: tisAppName can not be empty 

### ISSUE THREAD

**Issue by uchihayou** [qlangtech/tis#135]
安装TIS后，我运行FlinkSql时总是提示java.lang.IllegalStateException: tisAppName can not be empty in lib:file:/tmp/blobStore-fe65cb3d-3fc4-41ef-9840-5bd49e48c8ee/job_a98ed695370bf4c42a4f6307bf707c79/blob_p-5eb744a184a26204ccc3590ed4c2200bce6010d7-d5d8dab826f3eb5847a06839ab7553d5
请问这是什么原因导致的？

**Comment by baisui1981** [comment]
是否有更详细的异常栈，或者操作截图？可以进一步分析

**Comment by uchihayou** [comment]
重新安装FlinkSql后该问题没有复现，暂时关闭

**Comment by uchihayou** [comment]
重新安装FlinkSql后该问题没有复现，暂时关闭

**Comment by zhouhoo** [comment]
I have the same issure! I ran flink sql with flink-tis by "./bin/sql-client.sh" . I got error as bellow:
`Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
	at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:201)
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:161)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: tisAppName can not be empty in lib:file:/root/shen/flink-tis-1.13.1/opt/flink-sql-client_2.11-tis-1.13.1.jar
	at com.qlangtech.plugins.incr.flink.TISFlinkClassLoaderFactory.lambda$buildClientLoaderFactory$1(TISFlinkClassLoaderFactory.java:115)
	at org.apache.flink.client.ClientUtils.buildUserCodeClassLoader(ClientUtils.java:87)
	at org.apache.flink.table.client.gateway.context.SessionContext.create(SessionContext.java:197)
	at org.apache.flink.table.client.gateway.local.LocalContextUtils.buildSessionContext(LocalContextUtils.java:100)
	at org.apache.flink.table.client.gateway.local.LocalExecutor.openSession(LocalExecutor.java:91)
	at org.apache.flink.table.client.SqlClient.start(SqlClient.java:88)
	at org.apache.flink.table.client.SqlClient.startClient(SqlClient.java:187)
	... 1 more
Caused by: java.lang.IllegalStateException: tisAppName can not be empty in lib:file:/root/shen/flink-tis-1.13.1/opt/flink-sql-client_2.11-tis-1.13.1.jar
	at com.qlangtech.tis.plugin.PluginAndCfgsSnapshot.getRepositoryCfgsSnapshot(PluginAndCfgsSnapshot.java:164)
	at com.qlangtech.tis.plugin.PluginAndCfgsSnapshot.getRepositoryCfgsSnapshot(PluginAndCfgsSnapshot.java:115)
	at com.qlangtech.plugins.incr.flink.TISFlinkClassLoaderFactory.lambda$buildClientLoaderFactory$1(TISFlinkClassLoaderFactory.java:86)
	... 7 more
`


I know flink-tis is modified from origin flink, so flink sql client not supported any more? @uchihayou @baisui1981
