### ISSUE TITLE
mysql增量同步clickhouse部署异常

### ISSUE THREAD

**Issue by piaoyaoi** [qlangtech/tis#140]
java.lang.InstantiationException: java.lang.NoClassDefFoundError: com/qlangtech/tis/realtime/DefaultFlinkSourceHandle

**Comment by baisui1981** [comment]
``` shell
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.InstantiationException: java.lang.NoClassDefFoundError: com/qlangtech/tis/realtime/DefaultFlinkSourceHandle
	at com.qlangtech.plugins.incr.flink.TISFlinkClassLoaderFactory.lambda$buildClientLoaderFactory$1(TISFlinkClassLoaderFactory.java:120)
	at org.apache.flink.client.ClientUtils.buildUserCodeClassLoader(ClientUtils.java:87)
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:145)
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65)
	at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691)
	at com.qlangtech.tis.plugins.flink.client.FlinkClient.submitJar(FlinkClient.java:80)
	at com.qlangtech.plugins.incr.flink.launch.FlinkTaskNodeController.deploy(FlinkTaskNodeController.java:179)
	at com.qlangtech.plugins.incr.flink.launch.FlinkTaskNodeController.deploy(FlinkTaskNodeController.java:144)
	at com.qlangtech.tis.coredefine.module.action.TISK8sDelegate.deploy(TISK8sDelegate.java:136)
	at com.qlangtech.tis.coredefine.module.action.CoreAction.doDeployIncrSyncChannal(CoreAction.java:569)
	... 123 more
Caused by: java.lang.RuntimeException: java.lang.InstantiationException: java.lang.NoClassDefFoundError: com/qlangtech/tis/realtime/DefaultFlinkSourceHandle
	at com.qlangtech.tis.extension.ExtensionFinder$Sezpoz.removeByType(ExtensionFinder.java:168)
	at com.qlangtech.tis.extension.impl.ClassicPluginStrategy.lambda$removeByClassNameInFinders$0(ClassicPluginStrategy.java:64)
	at java.util.Collections$SingletonList.forEach(Collections.java:4824)
	at com.qlangtech.tis.extension.impl.ClassicPluginStrategy.removeByClassNameInFinders(ClassicPluginStrategy.java:63)
	at com.qlangtech.plugins.incr.flink.TISFlinkClassLoaderFactory.lambda$buildClientLoaderFactory$1(TISFlinkClassLoaderFactory.java:105)
	... 132 more
Caused by: java.lang.InstantiationException: java.lang.NoClassDefFoundError: com/qlangtech/tis/realtime/DefaultFlinkSourceHandle
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at com.qlangtech.tis.extension.ExtensionFinder$Sezpoz.removeByType(ExtensionFinder.java:160)
	... 136 more
Caused by: java.lang.NoClassDefFoundError: com/qlangtech/tis/realtime/DefaultFlinkSourceHandle
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at org.apache.tools.ant.AntClassLoader.defineClassFromData(AntClassLoader.java:1150)
	at org.apache.tools.ant.AntClassLoader.getClassFromStream(AntClassLoader.java:1318)
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1374)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1335)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.qlangtech.tis.extension.util.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:62)
	at com.qlangtech.tis.extension.util.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:91)
	at com.qlangtech.tis.extension.UberClassLoader.findClass(UberClassLoader.java:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
	... 137 more
Caused by: java.lang.ClassNotFoundException: by pieline_test.tpi,for:com.qlangtech.tis.realtime.DefaultFlinkSourceHandle
	at com.qlangtech.tis.extension.impl.ClassicPluginStrategy$DependencyClassLoader.findClass(ClassicPluginStrategy.java:589)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.tools.ant.AntClassLoader.findBaseClass(AntClassLoader.java:1405)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1102)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 152 more
```
