### ISSUE TITLE
error of create ftp source  that is sink to mysql

### ISSUE THREAD

**Issue by baisui1981** [qlangtech/tis#143]
ftp -> mysql 在设置schema 时候 报错
``` shell
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: null
	at com.qlangtech.tis.plugin.ds.ISelectedTab.getName(ISelectedTab.java:33)
	at com.qlangtech.tis.datax.IDataxProcessor$TableMap.<init>(IDataxProcessor.java:191)
	at com.qlangtech.tis.coredefine.module.action.DataxAction.doSaveWriterColsMeta(DataxAction.java:829)
	... 123 common frames omitted
```

**Comment by baisui1981** [comment]
另外，重构了dataX的ftp模块
1. 对FtpServer进行抽象封装
2. fileFormat进行抽象分装
3. fieldDelimiter 字段进行枚举化
4. 重构dataXftp reader/writer 模块，抽取FtpHelper对ftp服务端连接进行分装，可以共用
5. ftp reader 可支持writer中使用的全部压缩算法
6. ftp reader中可以切换使用 csv 和text 格式，原先只能使用csv
