### ISSUE TITLE
Oracle table column NUMBER(11,0) mapper to MySQL error

### ISSUE THREAD

**Issue by baisui1981** [qlangtech/tis#166]
Create Oracle and sink to MySQL table has an Error
```sql
  CREATE TABLE "AA" 
   (	"ID" VARCHAR2(36) NOT NULL ENABLE, 
	"PX" NUMBER(11,0), 
	 CONSTRAINT "PK_T_ZSTP_ORGAN" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   )
```

```shell
java.lang.IllegalStateException: col:PX{type=-5,typeName=, columnSize=-1, decimalDigits=null} colsize can not small than 1
	at com.qlangtech.tis.plugin.datax.DataxMySQLWriter$2.convertType(DataxMySQLWriter.java:215)
	at com.qlangtech.tis.plugin.datax.DataxMySQLWriter$2.access$600(DataxMySQLWriter.java:142)
	at com.qlangtech.tis.plugin.datax.DataxMySQLWriter$2$1.getMapperType(DataxMySQLWriter.java:161)
	at com.qlangtech.tis.plugin.datax.CreateTableSqlBuilder.build(CreateTableSqlBuilder.java:89)
	at com.qlangtech.tis.plugin.datax.DataxMySQLWriter.generateCreateDDL(DataxMySQLWriter.java:260)
	at com.qlangtech.tis.datax.impl.DataXCfgGenerator.generateTabCreateDDL(DataXCfgGenerator.java:307)
	at com.qlangtech.tis.datax.impl.DataXCfgGenerator.generateDataXAndSQLDDLFile(DataXCfgGenerator.java:280)
	at com.qlangtech.tis.datax.impl.DataXCfgGenerator.access$300(DataXCfgGenerator.java:52)
	at com.qlangtech.tis.datax.impl.DataXCfgGenerator$1.generateScriptFile(DataXCfgGenerator.java:150)
	at com.qlangtech.tis.datax.impl.DataXCfgGenerator.startGenerateCfg(DataXCfgGenerator.java:242)
	at com.qlangtech.tis.datax.impl.DataXCfgGenerator.startGenerateCfg(DataXCfgGenerator.java:145)
	at com.qlangtech.tis.coredefine.module.action.DataxAction.doGenerateDataxCfgs(DataxAction.java:550)
	at sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.qlangtech.tis.runtime.module.action.BasicModule.execute(BasicModule.java:115)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by baisui1981** [comment]
已经修复了
