### ISSUE TITLE
starrocks2.2.0 导入会每次都执行create table语句，表已经存在的时候也会执行

### ISSUE THREAD

**Issue by syhdh** [qlangtech/tis#167]
## 数据源
```
输入数据源：oracle 11.2
输出：starrocks 2.2.x
```

## 错误日志

```

2022-11-25 15:57:47 INFO Sr_import c.qlangtech.tis.plugin.PluginStore- load:/mnt/xincp/tis/tis-uber/data/cfg_repo/tis_plugin_config/db/ods_starRocks/com.qlangtech.tis.plugin.ds.DataSourceFactory.xml,this.loaded:false
2022-11-25 15:57:47 WARN Sr_import c.q.t.p.d.c.BasicDataXRdbmsWriter- TableNotFoundException{tableName='T_ZSTP_ROLE_MENU'}
2022-11-25 15:57:47 INFO Sr_import c.q.t.p.d.c.BasicDataXRdbmsWriter- create table:T_ZSTP_ROLE_MENU
   script:CREATE TABLE `T_ZSTP_ROLE_MENU`
(
    `ID`        VARCHAR(36) NOT NULL,
    `ROLE_ID`   VARCHAR(36),
    `MENU_ID`   VARCHAR(36),
    `CJSJ`      DATE,
    `GXSJ`      DATE,
    `SFSC`      VARCHAR(1)
)
 ENGINE=olap
PRIMARY KEY(`ID`)
DISTRIBUTED BY HASH(`ID`)
BUCKETS 10
PROPERTIES("replication_num" = "1")
2022-11-25 15:57:47 ERROR Sr_import c.a.datax.core.job.JobContainer- Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[RdbmsWriter-03], Description:[initialize 'tableName' faild]. - T_ZSTP_ROLE_MENU - java.lang.RuntimeException: CREATE TABLE `T_ZSTP_ROLE_MENU`
(
    `ID`        VARCHAR(36) NOT NULL,
    `ROLE_ID`   VARCHAR(36),
    `MENU_ID`   VARCHAR(36),
    `CJSJ`      DATE,
    `GXSJ`      DATE,
    `SFSC`      VARCHAR(1)
)
 ENGINE=olap
PRIMARY KEY(`ID`)
DISTRIBUTED BY HASH(`ID`)
BUCKETS 10
PROPERTIES("replication_num" = "1")
	at com.qlangtech.tis.plugin.datax.common.BasicDataXRdbmsWriter.process(BasicDataXRdbmsWriter.java:172)
	at com.qlangtech.tis.plugin.datax.common.BasicDataXRdbmsWriter.initWriterTable(BasicDataXRdbmsWriter.java:124)
	at com.qlangtech.tis.datax.impl.DataxWriter.process(DataxWriter.java:59)
	at com.alibaba.datax.plugin.writer.starrockswriter.TISStarRocksWriter$Job.init(TISStarRocksWriter.java:48)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:707)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.qlangtech.tis.datax.DataxExecutor.startEngine(DataxExecutor.java:409)
	at com.qlangtech.tis.datax.DataxExecutor.entry(DataxExecutor.java:397)
	at com.qlangtech.tis.datax.DataxExecutor.startWork(DataxExecutor.java:320)
	at com.qlangtech.tis.datax.DataxExecutor.exec(DataxExecutor.java:250)
	at com.qlangtech.tis.datax.DataxExecutor.exec(DataxExecutor.java:235)
	at com.qlangtech.tis.datax.DataxExecutor.main(DataxExecutor.java:182)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'T_ZSTP_ROLE_MENU' already exists
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.qlangtech.tis.plugin.datax.common.BasicDataXRdbmsWriter.process(BasicDataXRdbmsWriter.java:169)
	... 13 more

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:33)
	at com.alibaba.datax.plugin.writer.starrockswriter.TISStarRocksWriter$Job.init(TISStarRocksWriter.java:50)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:707)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:92)
	at com.qlangtech.tis.datax.DataxExecutor.startEngine(DataxExecutor.java:409)
	at com.qlangtech.tis.datax.DataxExecutor.entry(DataxExecutor.java:397)
	at com.qlangtech.tis.datax.DataxExecutor.startWork(DataxExecutor.java:320)
	at com.qlangtech.tis.datax.DataxExecutor.exec(DataxExecutor.java:250)
	at com.qlangtech.tis.datax.DataxExecutor.exec(DataxExecutor.java:235)
	at com.qlangtech.tis.datax.DataxExecutor.main(DataxExecutor.java:182)
Caused by: java.lang.RuntimeException: CREATE TABLE `T_ZSTP_ROLE_MENU`
(
    `ID`        VARCHAR(36) NOT NULL,
    `ROLE_ID`   VARCHAR(36),
    `MENU_ID`   VARCHAR(36),
    `CJSJ`      DATE,
    `GXSJ`      DATE,
    `SFSC`      VARCHAR(1)
)
 ENGINE=olap
PRIMARY KEY(`ID`)
DISTRIBUTED BY HASH(`ID`)
BUCKETS 10
PROPERTIES("replication_num" = "1")
	at com.qlangtech.tis.plugin.datax.common.BasicDataXRdbmsWriter.process(BasicDataXRdbmsWriter.java:172)
	at com.qlangtech.tis.plugin.datax.common.BasicDataXRdbmsWriter.initWriterTable(BasicDataXRdbmsWriter.java:124)
	at com.qlangtech.tis.datax.impl.DataxWriter.process(DataxWriter.java:59)
	at com.alibaba.datax.plugin.writer.starrockswriter.TISStarRocksWriter$Job.init(TISStarRocksWriter.java:48)
	... 10 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'T_ZSTP_ROLE_MENU' already exists
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
	at com.qlangtech.tis.plugin.datax.common.BasicDataXRdbmsWriter.process(BasicDataXRdbmsWriter.java:169)
	... 13 common frames omitted
2022-11-25 15:57:47 INFO Sr_import c.a.d.c.s.c.c.j.StandAloneJobContainerCommunicator- Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-11-25 15:57:47 ERROR Sr_import c.qlangtech.tis.datax.DataxExecutor- com.alibaba.datax.common.exception.DataXException: Code:[RdbmsWriter-03], Description:[initialize 'tableName' faild]. - T_ZSTP_ROLE_MENU - java.lang.RuntimeException: CREATE TABLE `T_ZSTP_ROLE_MENU`
(
    `ID`        VARCHAR(36) NOT NULL,
    `ROLE_ID`   VARCHAR(36),
    `MENU_ID`   VARCHAR(36),
    `CJSJ`      DATE,
    `GXSJ`      DATE,
    `SFSC`      VARCHAR(1)
)
 ENGINE=olap
PRIMARY KEY(`ID`)
```

**Comment by baisui1981** [comment]
目前我使用的是 sr 2.3.0 本地环境并没有发现有这个问题，无法复现，怀疑是不是sr 在2.2.0 有这个问题
