### ISSUE TITLE
[Oracle->Doris] Chunjun Source 实时同步异常

### ISSUE THREAD

**Issue by baisui1981** [qlangtech/tis#192]
使用数据库：Oracle11

Oracle Create Table DDL
``` sql
CREATE TABLE "DMP"."DMP_USER_" 
   (  "ID" NUMBER NOT NULL ENABLE, 
  "NAME" VARCHAR2(100), 
  "CREATED_TM" DATE, 
   CONSTRAINT "DMP_USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
   SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS, 
   SUPPLEMENTAL LOG DATA (ALL) COLUMNS
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
```
insert SQL
```sql
 INSERT INTO DMP.DMP_USER_(ID, NAME, CREATED_TM) VALUES (SEQ_DMP_USER.nextval, 'Wyw', SYSDATE);
```

Source 端采用oracle chunjun，
异常：
``` shell
  ava.lang.IllegalArgumentException: null
        at java.sql.Date.valueOf(Date.java:143) ~[?:1.8.0_251]
        at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.queryForPolling(JdbcInputFormat.java:742) ~[chunjun-connector-jdbc-base-1.12.5.jar:?]
        at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.reachedEnd(JdbcInputFormat.java:290) ~[chunjun-connector-jdbc-base-1.12.5.jar:?]
        at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:137) [chunjun-core-1.12.5.jar:?]
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) [flink-dist_2.11-tis-1.13.1.jar:tis-1.13.1]
```

@张三丰

**Comment by baisui1981** [comment]
已经修改了，之前在 OracleDataSourceFactory中设置了 Oracle Date类型转 转Types.DATE 的转化去掉了（Oracle 的Date类型实际上是 timestamp的类型）
``` java
//                if ("DATE".equalsIgnoreCase(type.typeName)) {
                // 由于Oracle的Date类型在实际上是精确到秒的，不能简单输出成Date类型
//                    return new DataType(Types.DATE, type.typeName, type.columnSize);
//                }
```
