### ISSUE TITLE
3.7 mysql 实时任务到 es有bug ,任务编译不了

### ISSUE THREAD

**Issue by tyler-whz** [qlangtech/tis#194]
<img width="1277" alt="截屏2023-03-22 09 42 44" src="https://user-images.githubusercontent.com/5018071/226782808-c07c29e9-a988-4e04-b860-a94d69cdd692.png">

**Comment by baisui1981** [comment]
收到 @伍宏泽

**Comment by tyler-whz** [comment]
<img width="1155" alt="截屏2023-03-22 15 49 05" src="https://user-images.githubusercontent.com/5018071/226834997-2bcec7b5-fad0-46c3-a096-7fa805aa91b4.png">
3.7  mysql实时监听到starrocks部署也有问题。手动创建 /opt/data/tis/libs/plugins目录就好了  部署上应该没提  @baisui1981

**Comment by baisui1981** [comment]
> <img alt="截屏2023-03-22 15 49 05" width="1155" src="https://user-images.githubusercontent.com/5018071/226834997-2bcec7b5-fad0-46c3-a096-7fa805aa91b4.png">
> 
> 3.7 mysql实时监听到starrocks部署也有问题。手动创建 /opt/data/tis/libs/plugins目录就好了 部署上应该没提 @baisui1981

已经修改了,TISFlinkClassLoaderFactory
```
private void makeDataDirUseable() {
        try {

            FileUtils.forceMkdir(PluginAndCfgsSnapshot.getPluginRootDir());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

**Comment by baisui1981** [comment]
前面几个异常都修复了，奇怪的是又报错下面这个类找不到的异常 `org.apache.avro.generic.GenericData$Array`
``` shell
Caused by: java.lang.ClassNotFoundException: org.apache.avro.generic.GenericData$Array
accepted plugins:tis-ds-mysql-plugin,tis-sink-elasticsearch7-plugin,tis-k8s-plugin,tis-flink-dependency,tis-datax-elasticsearch-plugin,tis-ds-mysql-v5-plugin,flink/mysql_es,tis-realtime-flink,tis-datax-common-rdbms-plugin,tis-flink-cdc-mysql-plugin,tis-datax-common-plugin
,scan plugins:tis-datax-common-plugin,tis-datax-common-rdbms-plugin,tis-ds-mysql-plugin,tis-ds-mysql-v8-plugin,tis-flink-dependency,tis-k8s-plugin,tis-realtime-flink,tis-chunjun-base-plugin,tis-datax-doris-starrocks-plugin,tis-flink-chunjun-doris-plugin,tis-ds-mysql-v5-plugin,tis-flink-chunjun-mysql-plugin,tis-datax-elasticsearch-plugin,tis-sink-elasticsearch7-plugin,tis-datax-kafka-plugin,tis-flink-chunjun-kafka-plugin,tis-flink-cdc-mysql-plugin,flink/mysql_es
faild plugins desc:FailedPlugins is Empty
	at com.qlangtech.tis.extension.UberClassLoader.findClass(UberClassLoader.java:137)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.qlangtech.plugins.incr.flink.TISChildFirstClassLoader.loadClassWithoutExceptionHandling(TISChildFirstClassLoader.java:52)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
```

**Comment by baisui1981** [comment]
前面几个异常都修复了，奇怪的是又报错下面这个类找不到的异常 `org.apache.avro.generic.GenericData$Array`
``` shell
Caused by: java.lang.ClassNotFoundException: org.apache.avro.generic.GenericData$Array
accepted plugins:tis-ds-mysql-plugin,tis-sink-elasticsearch7-plugin,tis-k8s-plugin,tis-flink-dependency,tis-datax-elasticsearch-plugin,tis-ds-mysql-v5-plugin,flink/mysql_es,tis-realtime-flink,tis-datax-common-rdbms-plugin,tis-flink-cdc-mysql-plugin,tis-datax-common-plugin
,scan plugins:tis-datax-common-plugin,tis-datax-common-rdbms-plugin,tis-ds-mysql-plugin,tis-ds-mysql-v8-plugin,tis-flink-dependency,tis-k8s-plugin,tis-realtime-flink,tis-chunjun-base-plugin,tis-datax-doris-starrocks-plugin,tis-flink-chunjun-doris-plugin,tis-ds-mysql-v5-plugin,tis-flink-chunjun-mysql-plugin,tis-datax-elasticsearch-plugin,tis-sink-elasticsearch7-plugin,tis-datax-kafka-plugin,tis-flink-chunjun-kafka-plugin,tis-flink-cdc-mysql-plugin,flink/mysql_es
faild plugins desc:FailedPlugins is Empty
	at com.qlangtech.tis.extension.UberClassLoader.findClass(UberClassLoader.java:137)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.qlangtech.plugins.incr.flink.TISChildFirstClassLoader.loadClassWithoutExceptionHandling(TISChildFirstClassLoader.java:52)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
```

**Comment by baisui1981** [comment]
fixed
