### ISSUE TITLE
通过插件池安装tis-hive-plugin失败

### ISSUE THREAD

**Issue by baisui1981** [qlangtech/tis#200]
通过插件池安装tis-hive-plugin失败，选择hive版本为`3.1.2` 安装失败
![屏幕快照 2023-03-28 下午12 48 02](https://user-images.githubusercontent.com/21274618/228131740-da488191-bf94-466b-8ba8-fec38e84d6c0.png)

详细异常
``` shell
java.lang.NullPointerException: plugin:tis-hive-plugin,for classifier:hive_3.1.2;hadoop_3.2.1,coord can not be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.qlangtech.tis.extension.model.UpdateSite.getTargetCoord(UpdateSite.java:785)
	at com.qlangtech.tis.extension.model.UpdateSite.access$400(UpdateSite.java:81)
	at com.qlangtech.tis.extension.model.UpdateSite$Plugin.deploy(UpdateSite.java:589)
	at com.qlangtech.tis.extension.model.UpdateSite$Plugin.deploy(UpdateSite.java:582)
	at com.qlangtech.tis.coredefine.module.action.PluginAction.doInstallPlugins(PluginAction.java:464)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.qlangtech.tis.runtime.module.action.BasicModule.execute(BasicModule.java:118)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by baisui1981** [comment]
fixed
