### ISSUE TITLE
[bug]ftp file data synchronization doris error

### ISSUE THREAD

**Issue by zq0757** [qlangtech/tis#207]
FTP file data synchronization error, Doris in step 3 times wrong table mapping: under Caused by: Java. Lang. An IllegalStateException: createDDLFiles can not be empty

**Comment by zq0757** [comment]
![1680254331947](https://user-images.githubusercontent.com/27143080/229080040-28f3ddbe-bd75-4353-9b1d-366a7e1e3884.jpg)

**Comment by zq0757** [comment]
Caused by: java.lang.RuntimeException: resType:DataApp,name:ftp2doris_demo
	at com.qlangtech.tis.coredefine.module.action.DataxAction.generateDataXCfgs(DataxAction.java:599)
	at com.qlangtech.tis.coredefine.module.action.DataxAction.doGenerateDataxCfgs(DataxAction.java:570)
	... 124 common frames omitted
Caused by: java.lang.IllegalStateException: createDDLFiles can not be empty 
	at com.qlangtech.tis.datax.impl.DataXCfgGenerator.startGenerateCfg(DataXCfgGenerator.java:274)
	at com.qlangtech.tis.datax.impl.DataXCfgGenerator.startGenerateCfg(DataXCfgGenerator.java:152)
	at com.qlangtech.tis.coredefine.module.action.DataxAction.generateDataXCfgs(DataxAction.java:592)
	... 125 common frames omitted
