### ISSUE TITLE
Failed to submit JobGraph

### ISSUE THREAD

**Issue by jeeinn** [qlangtech/tis#216]
tis version：3.7.0
MySQL 到 MySQL 数据同步，先使用了DataX批量构建正常。下面是紧接着使用实时同步时点击“部署”发生的错误：
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: /opt/data/tis/libs/plugins

```
com.qlangtech.tis.lang.TisException: java.util.concurrent.ExecutionException: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
	at com.qlangtech.tis.lang.TisException.create(TisException.java:88)
	at com.qlangtech.tis.coredefine.module.action.CoreAction.doDeployIncrSyncChannal(CoreAction.java:545)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
org.apache.flink.runtime.client.JobSubmissionException: Failed to submit job.
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$internalSubmitJob$2(Dispatcher.java:380)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: /opt/data/tis/libs/plugins
	at com.qlangtech.plugins.incr.flink.TISFlinkClassLoaderFactory$1.createClassLoader(TISFlinkClassLoaderFactory.java:210)
	at org.apache.flink.runtime.execution.librarycache.BlobLibraryCacheManager$LibraryCacheEntry.createUserCodeClassLoader(BlobLibraryCacheManager.java:286)
	at org.apache.flink.runtime.execution.librarycache.BlobLibraryCacheManager$LibraryCacheEntry.getOrResolveClassLoader(BlobLibraryCacheManager.java:253)
	at org.apache.flink.runtime.execution.librarycache.BlobLibraryCacheManager$LibraryCacheEntry.access$1000(BlobLibraryCacheManager.java:224)
	at org.apache.flink.runtime.execution.librarycache.BlobLibraryCacheManager$DefaultClassLoaderLease.getOrResolveClassLoader(BlobLibraryCacheManager.java:358)
	at org.apache.flink.runtime.dispatcher.JobMasterServiceLeadershipRunnerFactory.createJobManagerRunner(JobMasterServiceLeadershipRunnerFactory.java:97)
	at org.apache.flink.runtime.dispatcher.Dispatcher.createJobManagerRunner(Dispatcher.java:468)
	
```

**Comment by baisui1981** [comment]
先在 本地 ,创建plugin目录 ，这个异常已经再3.7.1 中修复
``` shell
mkdir -p /opt/data/tis/libs/plugins
```

**Comment by jeeinn** [comment]
感谢！手动创建试了下是可以的。
顺便问下我在咱们家的仓库里没有找到 v3.7.1 相关的 tag 和 release 😂

**Comment by baisui1981** [comment]
> 创建试了下是可以的。
> 顺便问下我在咱们家的仓库里没有找到 v3.7.1 相

3.7.1 还在测试中，还没有正式发布
