### ISSUE TITLE
mysql=>hive全量同步，校验hive数据源报错

### ISSUE THREAD

**Issue by NealZhi** [qlangtech/tis#223]
Caused by: java.lang.ClassNotFoundException: by tis-hive-plugin_hive_3.1.2_hadoop_3.2.1.tpi,for:org.apache.calcite.plan.RelOptRule
	at com.qlangtech.tis.extension.impl.ClassicPluginStrategy$DependencyClassLoader.findClass(ClassicPluginStrategy.java:455)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at org.apache.tools.ant.AntClassLoader.findBaseClass(AntClassLoader.java:1405)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1102)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 133 more
![image](https://github.com/qlangtech/tis/assets/36158629/824654de-f0d5-4178-bfe8-a730d90b5425)

**Comment by NealZhi** [comment]
tis为单节点安装，组件安装情况
![image](https://github.com/qlangtech/tis/assets/36158629/8a9379fe-471c-4a66-bddf-d605d474ba3f)

**Comment by baisui1981** [comment]
收到，之前集成测试环境使用的是 `hive_2.3.1;hadoop_2.7.3` 这个版本来测试的，可否告知一下你那边 使用的hadoop和hive 具体版本？

**Comment by NealZhi** [comment]
版本使用的是hadoop-3.3.3，hive-3.1.0，使用DataSophon（https://github.com/datasophon/datasophon）套件安装的

**Comment by baisui1981** [comment]
> 版本使用的是hadoop-3.3.3，hive-3.1.0，使用DataSophon（[https://github.com/datasophon/datasophon）套件安装的](https://github.com/datasophon/datasophon%EF%BC%89%E5%A5%97%E4%BB%B6%E5%AE%89%E8%A3%85%E7%9A%84)

ok ，我在本地也安装一下
