### ISSUE TITLE
zookeeper start error

### ISSUE THREAD

**Issue by graphnj** [qlangtech/tis#52]
2021-12-11 11:57:00,113 [myid:] - INFO  [SyncThread:0:FileTxnLog@216] - Creating new log file: log.1b
2021-12-11 11:57:00,117 [myid:] - ERROR [SyncThread:0:ZooKeeperCriticalThread@49] - Severe unrecoverable error, from thread : SyncThread:0
java.io.IOException: File too large
	at java.base/sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.pwrite(FileDispatcherImpl.java:68)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:109)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
	at java.base/sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:850)
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:836)
	at org.apache.zookeeper.server.persistence.FilePadding.padFile(FilePadding.java:78)
	at org.apache.zookeeper.server.persistence.FileTxnLog.append(FileTxnLog.java:230)
	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.append(FileTxnSnapLog.java:377)
	at org.apache.zookeeper.server.ZKDatabase.append(ZKDatabase.java:473)
	at org.apache.zookeeper.server.SyncRequestProcessor.run(SyncRequestProcessor.java:140)
2021-12-11 11:57:00,120 [myid:] - INFO  [SyncThread:0:ZooKeeperServerListenerImpl@42] - Thread SyncThread:0 exits, error code 1
2021-12-11 11:57:00,121 [myid:] - INFO  [SyncThread:0:SyncRequestProcessor@186] - SyncRequestProcessor exited!
2021-12-11 11:57:00,123 [myid:] - INFO  [main:NIOServerCnxn@1056] - Closed socket connection for client /127.0.0.1:51603 which had sessionid 0x1000100ca460000
2021-12-11 11:57:00,126 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@249] - NIOServerCnxn factory exited run method
2021-12-11 11:57:00,126 [myid:] - INFO  [main:ZooKeeperServer@502] - shutting down
2021-12-11 11:57:00,127 [myid:] - INFO  [main:SessionTrackerImpl@226] - Shutting down

**Comment by baisui1981** [comment]
before you launch the TIS ,the system port 2181 has been take up？

**Comment by graphnj** [comment]
zk in tis is running ok , but when tis  or more specified, when solr connecting zk, zk throw exception.

running env: mac 
% launchctl limit
	cpu         unlimited      unlimited      
	filesize    unlimited      unlimited      
	data        unlimited      unlimited      
	stack       8372224        67092480       
	core        0              unlimited      
	rss         unlimited      unlimited      
	memlock     unlimited      unlimited      
	maxproc     2000           2000           
	maxfiles    256            unlimited

**Comment by graphnj** [comment]
另:钉钉群二维码已过期

**Comment by baisui1981** [comment]
> 另:钉钉群二维码已过期

谢谢提醒，我疏忽了，另外，可以加我一下微信不:16660356

**Comment by baisui1981** [comment]
[https://github.com/qlangtech/tis/issues/53](https://github.com/qlangtech/tis/issues/53)
