### ISSUE TITLE
tis单机启动失败

### ISSUE THREAD

**Issue by BruceMaa** [qlangtech/tis#83]
version: 3.3.0

按照[官方文档](http://tis.pub/docs/install/uber/)选择单机版部署

执行启动命令后，一直在等待Solr，日志如下
```
[root@localhost tis-uber]# ./bin/tis.sh start
ZooKeeper JMX enabled by default
Using config: /opt/tis-uber/zookeeper/bin/../conf/zoo.cfg
Starting zookeeper ... STARTED
Waiting up to 180 seconds to see Solr running on port 8080 [|]  Still not seeing Solr listening on 8080 after 180 seconds!
tail: 无法打开"../logs/solr.log" 读取数据: 没有那个文件或目录
```

请问是需要自己预先启动Solr服务吗？

**Comment by baisui1981** [comment]
看一下 `./logs/solr-8080-console.log` 这个日志文件里面有没有啥异常信息

**Comment by BruceMaa** [comment]
`/etc/hosts` 配置如下

```
192.168.5.32   localhost localhost.localdomain localhost4 localhost4.localdomain4
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.5.30 k8s-master
192.168.5.31 k8s-node1
192.168.5.32 k8s-node2
```

`./logs/solr-8080-console.log`日志文件中异常信息如下

```
2022-01-07 10:40:51.822:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@60921b21{/tis-assemble,/tis-assemble,file:///opt/tis-uber/tis-assemble/webapp/,UNAVAILABLE}{file:///opt/tis-uber/web-start/../tis-assemble/webapp/}
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: ip can not be 127.0.0.1
        at com.qlangtech.tis.order.center.IndexSwapTaskflowLauncher.contextInitialized(IndexSwapTaskflowLauncher.java:124)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:933)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:892)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:356)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:825)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:407)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:371)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at com.qlangtech.tis.web.start.JettyTISRunner.start(JettyTISRunner.java:278)
        at com.qlangtech.tis.web.start.JettyTISRunner.start(JettyTISRunner.java:262)
        at com.qlangtech.tis.web.start.TisApp.start(TisApp.java:150)
        at com.qlangtech.tis.web.start.TisApp.main(TisApp.java:83)
Caused by:
java.lang.RuntimeException: java.lang.IllegalStateException: ip can not be 127.0.0.1
        at com.qlangtech.tis.solrj.util.ZkUtils.registerMyIp(ZkUtils.java:166)
        at com.qlangtech.tis.solrj.util.ZkUtils.registerAddress2ZK(ZkUtils.java:107)
        at com.qlangtech.tis.order.center.IndexSwapTaskflowLauncher.initIncrTransferStateCollect(IndexSwapTaskflowLauncher.java:174)
        at com.qlangtech.tis.order.center.IndexSwapTaskflowLauncher.contextInitialized(IndexSwapTaskflowLauncher.java:120)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:933)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:892)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:356)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:825)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:407)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:371)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at com.qlangtech.tis.web.start.JettyTISRunner.start(JettyTISRunner.java:278)
        at com.qlangtech.tis.web.start.JettyTISRunner.start(JettyTISRunner.java:262)
        at com.qlangtech.tis.web.start.TisApp.start(TisApp.java:150)
        at com.qlangtech.tis.web.start.TisApp.main(TisApp.java:83)
Caused by:
java.lang.IllegalStateException: ip can not be 127.0.0.1
        at com.qlangtech.tis.solrj.util.ZkUtils.registerMyIp(ZkUtils.java:158)
        at com.qlangtech.tis.solrj.util.ZkUtils.registerAddress2ZK(ZkUtils.java:107)
        at com.qlangtech.tis.order.center.IndexSwapTaskflowLauncher.initIncrTransferStateCollect(IndexSwapTaskflowLauncher.java:174)
        at com.qlangtech.tis.order.center.IndexSwapTaskflowLauncher.contextInitialized(IndexSwapTaskflowLauncher.java:120)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:933)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:892)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:356)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:825)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:407)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:371)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at com.qlangtech.tis.web.start.JettyTISRunner.start(JettyTISRunner.java:278)
        at com.qlangtech.tis.web.start.JettyTISRunner.start(JettyTISRunner.java:262)
        at com.qlangtech.tis.web.start.TisApp.start(TisApp.java:150)
        at com.qlangtech.tis.web.start.TisApp.main(TisApp.java:83)
```

**Comment by baisui1981** [comment]
hosts文件配置有问题，启动的时候不应该将自己节点ip解析成 127.0.0.1

参考：

```
因为进程启动时候会去拿本机的ip地址,所以要保证/etc/hosts文件中hostname 对应ip地址正确

  hostname
  # 得到上面显示的结果，例如：baisui-host-1
  ping baisui-host-1
  # 确认ip节点是否为本机ip无误,如不正确，请在/etc/hosts将正确的hostname与ip映射关系加上
```

**Comment by BruceMaa** [comment]
意思是我要在hosts文件中把下面的原始配置删掉？
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

这些配置别的服务可能也会用到，有没有单独配置的地方？

**Comment by baisui1981** [comment]
例如，先执行一下 `hostname`, 我得到 的是 `baisui-host-1`

然后 执行一下 
```
ping  baisui-host-1
```

如果这个执行结果是127.0.0.1 就是有问题了，解决办法就是到/etc/hosts 文件中加一行：

```
192.168.28.111 baisui-host-1
```
192.168.28.111为节点IP地址

最后再重启TIS，应该就好了

**Comment by BruceMaa** [comment]
已经启动成功。

解决步骤：
1. 修改hostname，不用默认的
```
sudo hostnamectl set-hostname bigdata
```
2. 在`/etc/hosts`中添加对应记录

```
192.168.5.32 bigdata
```

**Comment by baisui1981** [comment]
> 已经启动成功。
> 
> 解决步骤：
> 
> 1. 修改hostname，不用默认的
> 
> ```
> sudo hostnamectl set-hostname bigdata
> ```
> 
> 2. 在`/etc/hosts`中添加对应记录
> 
> ```
> 192.168.5.32 bigdata
> ```

恭喜启动成功，有需要的话 可以加我微信：16660356
